# fly.toml app configuration file generated for stripeback-cold-leaf-3140 on 2025-05-08T22:20:12+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stripeback-cold-leaf-3140'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
