name: Deploy to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'freepik-image-store/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Stripe/freepik-image-store/server 
            sudo git pull origin main 
            for id in $(docker ps -q --filter "publish=5000"); do
              docker stop $id || true
              docker rm $id || true
            done
            docker stop backend_container || true
            docker rm backend_container || true
            docker build -t backend_container .
            docker run --env-file .env -d -p 5000:5000 --name backend_container backend_container
